default: &default
  adapter: postgresql
  encoding: unicode
  # Run sudo -u postgres -i if you have not setup postgres before
  pool: 5
  timeout: 5000
  username: postgres
  password: <%= ENV['PGPASSWORD'] %>

development:
  <<: *default
  database: odin-facebook_development
  host: localhost

test:
  <<: *default
  host: localhost
  database: odin-facebook_test

production:
  <<: *default
  database: odin-facebook_production
  username: odin-facebook
  password: <%= ENV['ODIN-FACEBOOK_DATABASE_PASSWORD'] %>
