default: &default
  adapter: postgresql
  encoding: unicode
  # Run sudo -u postgres -i if you have not setup postgres before
  username: postgres
  pool: 5
  timeout: 5000
  port: 5432
  password: <%= ENV.fetch("PGPASSWORD") %>

development:
  <<: *default
  database: odin-facebook_development
  host: localhost

test:
  <<: *default
  database: odin-facebook_test
  host: localhost

production:
  <<: *default
  database: odin-facebook_production
  username: odin-facebook
  <%# password: <%= ENV['ODIN-FACEBOOK_DATABASE_PASSWORD'] %1> %>
