default: &default
  adapter: postgresql
  encoding: unicode
  # Run sudo -u postgres -i if you have not setup postgres before
  pool: 5
  timeout: 5000
  password: <%= ENV.fetch("PGPASSWORD") || '' %>

development:
  <<: *default
  database: odin-facebook_development
  host: localhost
  username: postgres

test:
  <<: *default
  database: odin-facebook_test
  host: localhost
  username: postgres

production:
  <<: *default
  database: odin-facebook_production
  username: odin-facebook
  <%# password: <%= ENV['ODIN-FACEBOOK_DATABASE_PASSWORD'] %1> %>
